### ISSUE TITLE
Dependency path hardcoded

### ISSUE THREAD

**Issue by b-pos465** [MoSimEngine/SimulatorComponentMetamodel#1]
@SebastianWeber

The following dependency path is hardcoded:

![image](https://user-images.githubusercontent.com/9197649/107236182-bcdf0a00-6a25-11eb-85c8-c8946ec45ae8.png)

**Comment by SebastianWeber** [comment]
Just delete the corresponding entry in the build path, there is another one using a local path. The library is only used for development purposes as maven uses the (different) version in its repository (8.2.0) for the build process.
